package com.smartallies.incident.model;

public enum WorkflowState {
    INITIAL,
    AWAITING_CLASSIFICATION_CONFIRMATION,
    CLASSIFICATION_CONFIRMED,
    COLLECTING_DETAILS,
    AWAITING_REPORT_CONFIRMATION,
    REPORT_READY,
    COMPLETED,
    EMERGENCY_ACTIVE
}
